Weekies\RecipesBundle\Entity\Recipe:
    type: entity
    table: null
    repositoryClass: Weekies\RecipesBundle\Entity\RecipeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        amountOfPeople:
            type: integer
        cookingTime:
            type: integer
        rating:
            type: float
        image:
            type: blob
        source:
            type: string
            length: 255
        url:
            type: string
            length: 512
    oneToMany:
            recipeIngredients:
                targetEntity: RecipeIngredient
                mappedBy: recipe
                cascade: ["persist"]
    uniqueConstraints:
        search_idx:
            columns: [ url ]
    lifecycleCallbacks: {  }
