Weekies\RecipesBundle\Entity\Recipe:
    type: entity
    table: null
    repositoryClass: Weekies\RecipesBundle\Entity\RecipeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        amountOfPeople:
            type: integer
        cookingTime:
            type: integer
        rating:
            type: float
        image:
            type: blob
            nullable: TRUE
        source:
            type: string
            length: 255
            nullable: TRUE
        url:
            type: string
            length: 512
            nullable: TRUE
    oneToMany:
            recipeIngredients:
                targetEntity: RecipeIngredient
                mappedBy: recipe
                cascade: ["persist"]
#    uniqueConstraints:
#        url_idx:
#            columns: [ url ]
    lifecycleCallbacks: {  }
