<?php

namespace Weekies\MenuGenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DinnerHasRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinnerHasRecipeRepository extends EntityRepository
{
}
